name: publish-hatch-protobuf

on:
  push:
    tags:
      - v*

concurrency:
  group: publish-${{ github.head_ref }}


jobs:
  build:
    name: Build wheels and source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          # version shouldn't matter that much, but best to be consistent
          python-version: 3.12
      - name: Install build dependencies
        run: python -m pip install --upgrade hatch
      - name: Build
        run: python -m hatch build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          if-no-files-found: error

  publish:
    name: Publish release
    needs:
      - build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Push package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.14
